#!/usr/bin/env bash

#/ command: rundeck-keys:metadata: "get the key metadata"
#/ usage: rerun rundeck-keys:metadata  --keypath <>  --url <$RUNDECK_URL> [ --username <$RUNDECK_USER>] [ --password <$RUNDECK_PASSWORD>] [ --apikey <$RUNDECK_APIKEY>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: KEYPATH URL USERNAME PASSWORD APIKEY

. $RERUN_MODULE_DIR/lib/functions.sh metadata || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

KEYPATH=${KEYPATH#keys/}


CURL_OUT=$(mktemp -t curl.out.XXXXX)
trap 'rm $CURL_OUT' EXIT; # cleanup on exit

rundeck_authenticate -u "$URL" -U "${USERNAME:-}" -p "${PASSWORD:-}" -k "${APIKEY:-}"

if ! http_code=$(rundeck_curl -w "%{http_code}" -H 'Accept: application/xml' \
    -X GET "${URL}/api/11/storage/keys/$KEYPATH" -o $CURL_OUT  2>/dev/null)
then
	rerun_die 3 "curl request failed (exit code: $?)"
fi

# If the Accept request header matches */* or application/octet-stream, 
# or a password if the request header matches */*,
# or application/x-rundeck-data-password,
# will result in a 403 Unauthorized response.


case ${http_code:-} in
	200) : ;; # successful
	403) rerun_die 1 "Key metadata for private key data is not authorized." ;;
	404) rerun_die 1 "Key path not found: $KEYPATH" ;;
	* ) rerun_die 3 "API error ${http_code:-} : GET ${URL}/api/11/storage/keys/$KEYPATH.";;
esac  

xmlstarlet fo $CURL_OUT

xmlstarlet sel -t -m "/resource" \
	-v "@path" 	-o ":" \
	-n -o "  url: " -v @url \
	-n -o "  content-type: " -v resource-meta/Rundeck-content-type \
	-n -o "  creation-time: " -v resource-meta/Rundeck-content-creation-time \
	-n -o "  modify-time: " -v resource-meta/Rundeck-content-modify-time \
	-n -o "  created-username: " -v resource-meta/Rundeck-auth-created-username \
	-n -o "  modified-username: " -v resource-meta/Rundeck-auth-modified-username \
	-n $CURL_OUT


# Done. Exit with last command exit status.
exit $?

