#!/usr/bin/env bash

#/ command: rundeck-keys:delete: "delete the key"
#/ usage: rerun rundeck-keys:delete  --keypath <>  --url <$RUNDECK_URL> [ --username <$RUNDECK_USER>] [ --password <$RUNDECK_PASSWORD>] [ --apikey <$RUNDECK_APIKEY>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: KEYPATH URL USERNAME PASSWORD APIKEY

. $RERUN_MODULE_DIR/lib/functions.sh delete || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

KEYPATH=${KEYPATH#keys/}

CURL_OUT=$(mktemp -t curl.out.XXXXX)
trap 'rm $CURL_OUT' EXIT; # cleanup on exit

rundeck_authenticate -u "$URL" -U "${USERNAME:-}" -p "${PASSWORD:-}" -k "${APIKEY:-}"


if ! http_code=$(rundeck_curl -w "%{http_code}" -H 'Accept: application/xml' \
    -X DELETE "${URL}/api/11/storage/keys/$KEYPATH" -o $CURL_OUT)
then
	rerun_die 3 "curl request failed (exit code: $?)"

fi

case ${http_code:-} in
	204) : ;; # successful removal
	404) rerun_log debug "key did not exist" ;;
	40*) rerun_die 1 "$(xmlstarlet sel -t -m / -v error $CURL_OUT)" ;;
	* ) rerun_die 3 "API error ${http_code:-}: DELETE ${URL}/api/11/storage/keys/$KEYPATH.)" ;;
esac

# Done. Exit with last command exit status.
exit $?

