#!/usr/bin/env bash

#/ command: rundeck-keys:list: "list the keys"
#/ usage: rerun rundeck-keys:list  --url <$RUNDECK_URL> [ --username <$RUNDECK_USER>] [ --password <$RUNDECK_PASSWORD>] [ --apikey <$RUNDECK_APIKEY>]  --keypath <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: URL USERNAME PASSWORD APIKEY KEYPATH

. $RERUN_MODULE_DIR/lib/functions.sh list || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

#
# Read authentication credentials
#
rundeck_authenticate -u "$URL" -U "${USERNAME:-}" -p "${PASSWORD:-}" -k "${APIKEY:-}"


CURL_OUT=$(mktemp -t curl.out.XXXXX)
trap 'rm $CURL_OUT' EXIT; # cleanup on exit

# normalize the root path. 
case $KEYPATH in
	/) KEYPATH= ;;
	keys) KEYPATH= ;;
esac
# Remove keys/ prefix if it exists.
KEYPATH=${KEYPATH#keys/}

if ! http_code=$(rundeck_curl -w "%{http_code}" -H 'Accept: application/xml' \
    -X GET "${URL}/api/11/storage/keys/${KEYPATH}" -o $CURL_OUT 2>/dev/null)
then
	rerun_die 3 "curl request failed (exit code: $?)"
fi

case ${http_code:-} in
	200) : ;; # successful 
	404) rerun_die 1 "Key path not found: $KEYPATH" ;;
	* ) rerun_die 3 "API error (HTTP response: $http_code, GET ${URL}/api/11/storage/keys/${KEYPATH})." ;;
esac  

#xmlstarlet fo $CURL_OUT

count=$(xmlstarlet sel -t -m "/resource/contents" -v @count $CURL_OUT)

if ! subdirs=($(xmlstarlet sel -t -m "/resource/contents/resource[@type='directory']" -v "@path" -n $CURL_OUT))
then
	rerun_log debug "no sub directories in keypath $KEYPATH"
fi

if ! xmlstarlet sel -t -m "//resource[@type='file']" \
	-v "@path" \
	-n $CURL_OUT
then
	:; # there were no files in this listing.
fi

# Make recursive call to `list` for subdirectories
if (( ${#subdirs[*]:-} > 0 ))
then
	rerun_log debug "There are ${#subdirs[*]} subdirs: ${subdirs[*]}"
	clopts=(--url $URL)
	[[ -n "${USERNAME:-}" ]] && clopts=(${clopts[*]} --username $USERNAME)
	[[ -n "${PASSWORD:-}" ]] && clopts=(${clopts[*]} --password $PASSWORD) 
	[[ -n "${APIKEY:-}"   ]] && clopts=(${clopts[*]} --apikey $APIKEY)

	for subdir in ${subdirs[*]}
	do
		rerun_log debug " - rerun rundeck-keys:list --keypath ${subdir}"
		rerun rundeck-keys:list --keypath ${subdir} ${clopts[*]}
	done
fi	
# Done. Exit with last command exit status.
exit $?

